---
dist: xenial
language: python
python:
  - '3.7'
  - '3.6'
install:
  - pip install coveralls
  - make venv
script:
  - make test
  - if test "$TRAVIS_PYTHON_VERSION" == '3.7'; then venv/bin/check-requirements; fi
after_success:
  - coveralls
cache:
  pip: true
  directories:
    - $HOME/.cache/pre-commit
